version: 0.0
os: linux
files:
  - source: /home/ec2-user/Ca-Lad
    destination: /home/ec2-user/Ca-Lad
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

